//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace game.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class pPrice
    {
        public int gId { get; set; }
        [DisplayName("遊戲標題")]
        [Required(ErrorMessage = "標題不可空白")]
        public string gTitle { get; set; }
        [DisplayName("遊戲製作公司")]
        [Required(ErrorMessage = "不可空白")]
        public string gCompany { get; set; }
        [DisplayName("遊戲發售日期")]
        [Required(ErrorMessage = "不可空白")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy/MM/dd}")]
        public Nullable<System.DateTime> gDate { get; set; }
        [DisplayName("遊戲價格")]
        [Required(ErrorMessage = "價格不可空白或為負數")]
        [Range(0, 99999999)]
        public Nullable<decimal> Price { get; set; }
        [DisplayName("遊戲圖片")]
        public string Picture { get; set; }
        [DisplayName("遊戲相關影片")]
        public string video { get; set; }
        [DisplayName("遊戲尺寸")]
        [Required(ErrorMessage = "不可空白")]
        [Range(0, 99)]
        public Nullable<decimal> size { get; set; }
        [DisplayName("遊戲類型")]
        [Required(ErrorMessage = "不可空白")]
        public string type { get; set; }
        [DisplayName("可遊玩人數")]
        [Required(ErrorMessage = "不可空白")]
        public string player { get; set; }
        [DisplayName("可使用語言")]
        [Required(ErrorMessage = "不可空白")]
        public string language { get; set; }
        [DisplayName("購物連結")]
        [Required(ErrorMessage = "不可空白")]
        public string purchase { get; set; }
    }
}
